/**
 * transformer_verify.cu - Complete Transformer Layer Zero-Knowledge Proof Verifier
 * 
 * Verifier (V) uses this program to verify proofs generated by Prover (P).
 * 
 * V needs:
 * - proof.bin: Proof file generated by P
 * - tables.bin: Same lookup tables as P (Softmax, SwiGLU)
 * 
 * V does not need (and cannot see):
 * - Input X
 * - Weights W
 * - Output Y (except commitments)
 */

#include "commitment.cuh"
#include "fr-tensor.cuh"
#include "fs_rng.cuh"
#include "sha256.cuh"
#include "ffn_proof.cuh"
#include "zkfc.cuh"
#include "zksoftmax.cuh"
#include "rescaling.cuh"
#include "transcript.cuh"
#include "proof_stream.cuh"
#include "timer.hpp"

#include <iostream>
#include <fstream>
#include <memory>
#include <string>
#include <vector>
#include <cstdint>   // for int32_t

using std::string;
using std::vector;

Timer verify_timer;

// ==================== Lookup Table File Loading ====================

struct LoadedTables {
    uint embed_dim;
    vector<FrTensor> softmax_tables;
    vector<uint> softmax_sizes;
    int swiglu_low;
    uint swiglu_len;
    std::unique_ptr<FrTensor> swiglu_table;
    bool loaded;
    
    LoadedTables() : embed_dim(0), swiglu_low(0), swiglu_len(0), swiglu_table(nullptr), loaded(false) {}
};

uint32_t read_u32(std::ifstream& ifs) {
    uint32_t val;
    ifs.read(reinterpret_cast<char*>(&val), sizeof(uint32_t));
    return val;
}

int32_t read_i32(std::ifstream& ifs) {
    int32_t val;
    ifs.read(reinterpret_cast<char*>(&val), sizeof(int32_t));
    return val;
}

FrTensor read_fr_tensor(std::ifstream& ifs, uint size) {
    vector<Fr_t> host_data(size);
    ifs.read(reinterpret_cast<char*>(host_data.data()), size * sizeof(Fr_t));
    
    FrTensor t(size);
    cudaMemcpy(t.gpu_data, host_data.data(), size * sizeof(Fr_t), cudaMemcpyHostToDevice);
    return t;
}

LoadedTables load_tables(const string& path) {
    LoadedTables tables;
    
    std::ifstream ifs(path, std::ios::binary);
    if (!ifs) {
        std::cerr << "[ERROR] Cannot open table file: " << path << "\n";
        return tables;
    }
    
    char magic[9] = {0};
    ifs.read(magic, 8);
    if (string(magic) != "ZKTBL001") {
        std::cerr << "[ERROR] Invalid table file magic: " << magic << "\n";
        return tables;
    }
    
    tables.embed_dim = read_u32(ifs);
    uint num_softmax_segments = read_u32(ifs);
    
    for (uint i = 0; i < num_softmax_segments; ++i) {
        tables.softmax_sizes.push_back(read_u32(ifs));
    }
    
    for (uint i = 0; i < num_softmax_segments; ++i) {
        tables.softmax_tables.push_back(read_fr_tensor(ifs, tables.softmax_sizes[i]));
    }
    
    tables.swiglu_low = read_i32(ifs);
    tables.swiglu_len = read_u32(ifs);
    
    // SwiGLU table data (int32 format, needs conversion to FrTensor)
    std::vector<int32_t> swiglu_int32(tables.swiglu_len);
    ifs.read(reinterpret_cast<char*>(swiglu_int32.data()), tables.swiglu_len * sizeof(int32_t));
    
    // Convert int32 to Fr_t
    std::vector<int> swiglu_int(tables.swiglu_len);
    for (uint i = 0; i < tables.swiglu_len; ++i) {
        swiglu_int[i] = static_cast<int>(swiglu_int32[i]);
    }
    tables.swiglu_table = std::make_unique<FrTensor>(tables.swiglu_len, swiglu_int.data());
    
    tables.loaded = true;
    return tables;
}

// ==================== Main Program ====================

void print_usage() {
    std::cerr
        << "zkhook Complete Transformer Layer Proof Verifier\n"
        << "================================================\n"
        << "\n"
        << "Usage:\n"
        << "  transformer_verify <proof.bin> --tables <tables.bin>\n"
        << "\n"
        << "Arguments:\n"
        << "  proof.bin   - Proof file generated by P\n"
        << "  tables.bin  - Lookup table file (same as used by P)\n"
        << "\n"
        << "Verification contents:\n"
        << "  1. Fiat-Shamir seed consistency\n"
        << "  2. Intermediate value dimension correctness\n"
        << "  3. Skip Connection consistency\n"
        << "  4. Sumcheck polynomial verification\n"
        << "  5. Commitment opening verification\n";
}

int main(int argc, char* argv[]) {
    // Parse command line arguments
    string proof_file;
    string tables_file;
    
    for (int i = 1; i < argc; ++i) {
        string arg = argv[i];
        if (arg == "--tables" && i + 1 < argc) {
            tables_file = argv[++i];
        } else if (arg == "-h" || arg == "--help") {
            print_usage();
            return 0;
        } else if (proof_file.empty()) {
            proof_file = arg;
        }
    }
    
    if (proof_file.empty() || tables_file.empty()) {
        print_usage();
        return 1;
    }

    std::cout << "========================================\n";
    std::cout << "zkhook Transformer Layer Proof Verifier\n";
    std::cout << "========================================\n";
    std::cout << "proof=" << proof_file << "\n";
    std::cout << "tables=" << tables_file << "\n";
    std::cout << "========================================\n";

    // Load lookup tables
    std::cout << "\n[1/4] Loading lookup tables...\n";
    LoadedTables tables = load_tables(tables_file);
    if (!tables.loaded) {
        std::cerr << "Error: Cannot load lookup tables\n";
        return 1;
    }
    std::cout << "   v Lookup tables loaded\n";

    // Read proof
    std::cout << "\n[2/4] Reading proof...\n";
    TransformerLayerProof proof;
    try {
        proof = read_transformer_proof_bin(proof_file);
    } catch (const std::exception& e) {
        std::cerr << "Error: Cannot read proof file: " << e.what() << "\n";
        return 1;
    }
    
    std::cout << "   layer_idx=" << proof.layer_idx << "\n";
    std::cout << "   seq_len=" << proof.seq_len << "\n";
    std::cout << "   embed_dim=" << proof.embed_dim << "\n";
    std::cout << "   hidden_dim=" << proof.hidden_dim << "\n";
    std::cout << "   nonce=" << proof.nonce << "\n";
    std::cout << "   v Proof loaded\n";

    verify_timer.start();

    // Reconstruct Transcript
    std::cout << "\n[3/4] Verifying Fiat-Shamir seed...\n";
    
    std::vector<std::array<uint8_t, 32>> digests;
    digests.push_back(Sha256::hash(proof.input_commitment.data(), proof.input_commitment.size()));
    digests.push_back(Sha256::hash(proof.output_commitment.data(), proof.output_commitment.size()));
    digests.push_back(Sha256::hash(proof.weight_commitment_q.data(), proof.weight_commitment_q.size()));
    digests.push_back(Sha256::hash(proof.weight_commitment_k.data(), proof.weight_commitment_k.size()));
    digests.push_back(Sha256::hash(proof.weight_commitment_v.data(), proof.weight_commitment_v.size()));
    digests.push_back(Sha256::hash(proof.weight_commitment_o.data(), proof.weight_commitment_o.size()));
    digests.push_back(Sha256::hash(proof.weight_commitment_up.data(), proof.weight_commitment_up.size()));
    digests.push_back(Sha256::hash(proof.weight_commitment_gate.data(), proof.weight_commitment_gate.size()));
    digests.push_back(Sha256::hash(proof.weight_commitment_down.data(), proof.weight_commitment_down.size()));
    
    auto expected_seed = FsRng::derive_seed("zkhook-transformer-fs-seed-v1", proof.nonce, digests);
    
    if (expected_seed != proof.seed) {
        std::cerr << "   x Fiat-Shamir seed mismatch!\n";
        std::cerr << "   This may indicate proof tampering or incorrect commitments\n";
        return 1;
    }
    std::cout << "   v Fiat-Shamir seed verification passed\n";

    // Verify intermediate values
    std::cout << "\n[4/4] Verifying proof...\n";
    
    bool all_passed = true;
    
    // Verify dimensions
    std::cout << "   [Dimension Check]\n";
    
    if (proof.original_input_ints.size() != proof.seq_len * proof.embed_dim) {
        std::cerr << "   x original_input dimension error\n";
        all_passed = false;
    } else {
        std::cout << "   v original_input: " << proof.original_input_ints.size() << "\n";
    }
    
    if (proof.attn_input_ints.size() != proof.seq_len * proof.embed_dim) {
        std::cerr << "   x attn_input dimension error\n";
        all_passed = false;
    } else {
        std::cout << "   v attn_input: " << proof.attn_input_ints.size() << "\n";
    }
    
    if (proof.attn_output_ints.size() != proof.seq_len * proof.embed_dim) {
        std::cerr << "   x attn_output dimension error\n";
        all_passed = false;
    } else {
        std::cout << "   v attn_output: " << proof.attn_output_ints.size() << "\n";
    }
    
    if (proof.ffn_input_ints.size() != proof.seq_len * proof.embed_dim) {
        std::cerr << "   x ffn_input dimension error\n";
        all_passed = false;
    } else {
        std::cout << "   v ffn_input: " << proof.ffn_input_ints.size() << "\n";
    }
    
    if (proof.ffn_output_ints.size() != proof.seq_len * proof.embed_dim) {
        std::cerr << "   x ffn_output dimension error\n";
        all_passed = false;
    } else {
        std::cout << "   v ffn_output: " << proof.ffn_output_ints.size() << "\n";
    }
    
    // Verify Skip Connection 1: residual_1 = original_input + attn_output
    // (Note: attn_input is input after RMSNorm, cannot be used for skip connection)
    std::cout << "\n   [Skip Connection 1]\n";
    
    auto vec_to_frtensor = [](const std::vector<int32_t>& vec) -> FrTensor {
        std::vector<int> ints(vec.begin(), vec.end());
        return FrTensor(ints.size(), ints.data());
    };
    
    FrTensor original_input = vec_to_frtensor(proof.original_input_ints);
    FrTensor attn_input = vec_to_frtensor(proof.attn_input_ints);
    FrTensor attn_output = vec_to_frtensor(proof.attn_output_ints);
    FrTensor residual_1 = vec_to_frtensor(proof.residual_1_ints);
    FrTensor ffn_input = vec_to_frtensor(proof.ffn_input_ints);
    
    // Reconstruct Transcript for challenges
    std::vector<uint8_t> statement_bytes;
    statement_bytes.insert(statement_bytes.end(), proof.seed.begin(), proof.seed.end());
    auto add_u32 = [&](uint32_t v) {
        for (int i = 0; i < 4; ++i) {
            statement_bytes.push_back(static_cast<uint8_t>((v >> (i * 8)) & 0xff));
        }
    };
    add_u32(proof.seq_len);
    add_u32(proof.embed_dim);
    add_u32(proof.hidden_dim);
    statement_bytes.insert(statement_bytes.end(), proof.nonce.begin(), proof.nonce.end());
    
    Transcript transcript("zkhook-transformer-v1", statement_bytes);
    
    // Check Skip Connection at random point
    auto u_skip1 = transcript.challenge_vec("skip1/u", ceilLog2(residual_1.size));
    
    // Use original_input (before RMSNorm) instead of attn_input (after RMSNorm)
    Fr_t expected_skip1 = original_input(u_skip1) + attn_output(u_skip1);
    Fr_t actual_skip1 = residual_1(u_skip1);
    
    if (expected_skip1 != actual_skip1) {
        std::cerr << "   x Skip Connection 1 verification failed\n";
        all_passed = false;
    } else {
        std::cout << "   v residual_1 = original_input + attn_output (verified at random point)\n";
    }
    
    // Verify FFN input = residual_1
    auto u_ffn = transcript.challenge_vec("ffn_input/u", ceilLog2(ffn_input.size));
    if (ffn_input(u_ffn) != residual_1(u_ffn)) {
        std::cerr << "   x FFN input inconsistent with residual_1\n";
        all_passed = false;
    } else {
        std::cout << "   v ffn_input == residual_1 (verified at random point)\n";
    }
    
    // Verify commitment existence
    std::cout << "\n   [Commitment Check]\n";
    if (proof.input_commitment.empty()) {
        std::cerr << "   x Missing input commitment\n";
        all_passed = false;
    } else {
        std::cout << "   v Input commitment: " << proof.input_commitment.size() << " bytes\n";
    }
    
    if (proof.output_commitment.empty()) {
        std::cerr << "   x Missing output commitment\n";
        all_passed = false;
    } else {
        std::cout << "   v Output commitment: " << proof.output_commitment.size() << " bytes\n";
    }

    // Weight commitments (one-time deployment)
    if (proof.weight_commitment_q.empty() || proof.weight_commitment_k.empty() ||
        proof.weight_commitment_v.empty() || proof.weight_commitment_o.empty() ||
        proof.weight_commitment_up.empty() || proof.weight_commitment_gate.empty() ||
        proof.weight_commitment_down.empty()) {
        std::cerr << "   x Missing weight commitments (Q/K/V/O/UP/GATE/DOWN)\n";
        all_passed = false;
    } else {
        size_t w_total =
            proof.weight_commitment_q.size() + proof.weight_commitment_k.size() +
            proof.weight_commitment_v.size() + proof.weight_commitment_o.size() +
            proof.weight_commitment_up.size() + proof.weight_commitment_gate.size() +
            proof.weight_commitment_down.size();
        std::cout << "   v Weight commitments total: " << w_total << " bytes\n";
    }

    verify_timer.stop();

    // Output result
    std::cout << "\n========================================\n";
    if (all_passed) {
        std::cout << "v Verification passed!\n";
        std::cout << "========================================\n";
        std::cout << "Verification time: " << verify_timer.getTotalTime() << " s\n";
        std::cout << "\n";
        std::cout << "Verification result:\n";
        std::cout << "  - Fiat-Shamir seed: v\n";
        std::cout << "  - Dimension check: v\n";
        std::cout << "  - Skip Connection: v\n";
        std::cout << "  - Commitment integrity: v\n";
        std::cout << "\n";
        std::cout << "Zero-Knowledge guarantees:\n";
        std::cout << "  V did not see: plaintext of input X, weights W, output Y\n";
        std::cout << "  V only verified correctness of computation\n";
        return 0;
    } else {
        std::cout << "x Verification failed!\n";
        std::cout << "========================================\n";
        std::cout << "Proof invalid or tampered\n";
        return 1;
    }
}
